import type { AIModel, MCPServer } from './types';

/**
 * Seeded from odh-dashboard Cypress mocks + shaped to exercise prod row variations:
 * status, endpoints, playground CTAs, embedding/ASR, MaaS, custom endpoint kebab.
 */
export const MOCK_AI_MODELS: AIModel[] = [
  {
    model_name: 'Llama-3.2-3B-Instruct',
    model_id: 'Llama-3.2-3B-Instruct',
    serving_runtime: 'vllm',
    api_protocol: 'openai',
    version: '1.0.0',
    usecase: 'General chat, Code generation',
    description: 'Meta Llama 3.2 3B Instruct model',
    endpoints: ['internal: http://llama-3-2-3b.svc.cluster.local:8080'],
    status: 'Running',
    display_name: 'Llama 3.2 3B Instruct',
    model_source_type: 'namespace',
    model_type: 'llm',
    capabilities: ['text-generation', 'tools'],
    internalEndpoint: 'http://llama-3-2-3b.svc.cluster.local:8080',
    inPlayground: false,
  },
  {
    model_name: 'granite-3-8b-instruct',
    model_id: 'granite-3-8b-instruct',
    serving_runtime: 'vllm',
    api_protocol: 'openai',
    version: '1.0.0',
    usecase: 'Enterprise chat, Summarization',
    description: 'IBM Granite 3 8B Instruct via Models as a Service',
    endpoints: ['external: https://maas.apps.example.com/v1'],
    status: 'Running',
    display_name: 'Granite 3 8B Instruct',
    model_source_type: 'maas',
    model_type: 'llm',
    capabilities: ['text-generation', 'vision'],
    externalEndpoint: 'https://maas.apps.example.com/v1',
    inPlayground: true,
  },
  {
    model_name: 'claude-sonnet-4',
    model_id: 'claude-sonnet-4',
    serving_runtime: 'external',
    api_protocol: 'openai',
    version: '1.0.0',
    usecase: 'Reasoning, Analysis, Code review',
    description: 'Anthropic Claude Sonnet 4 via LiteLLM proxy',
    endpoints: ['external: https://litellm.apps.example.com/v1'],
    status: 'Running',
    display_name: 'Anthropic Claude Sonnet 4',
    model_source_type: 'custom_endpoint',
    model_type: 'llm',
    capabilities: ['text-generation', 'tools', 'vision'],
    externalEndpoint: 'https://litellm.apps.example.com/v1',
    inPlayground: false,
  },
  {
    model_name: 'gemini-2-5-flash',
    model_id: 'gemini-2-5-flash',
    serving_runtime: 'external',
    api_protocol: 'openai',
    version: '1.0.0',
    usecase: 'Classification, Image generation',
    description: 'Google Gemini 2.5 Flash via LiteLLM proxy',
    endpoints: ['external: https://litellm.apps.example.com/gemini'],
    status: 'Stop',
    display_name: 'Gemini 2.5 Flash (External API)',
    model_source_type: 'custom_endpoint',
    model_type: 'llm',
    capabilities: ['text-generation', 'vision'],
    externalEndpoint: 'https://litellm.apps.example.com/gemini',
    inPlayground: false,
  },
  {
    model_name: 'nomic-embed-text',
    model_id: 'nomic-embed-text',
    serving_runtime: 'vllm',
    api_protocol: 'openai',
    version: '1.0.0',
    usecase: 'Embeddings for RAG',
    description: 'Embedding model for vector stores',
    endpoints: ['internal: http://nomic-embed.svc.cluster.local:8080'],
    status: 'Running',
    display_name: 'Nomic Embed Text',
    model_source_type: 'namespace',
    model_type: 'embedding',
    capabilities: ['text-generation'],
    internalEndpoint: 'http://nomic-embed.svc.cluster.local:8080',
    inPlayground: true,
  },
  {
    model_name: 'whisper-large-v3',
    model_id: 'whisper-large-v3',
    serving_runtime: 'vllm',
    api_protocol: 'openai',
    version: '1.0.0',
    usecase: 'Speech to text',
    description: 'Audio transcription model used in playground settings',
    endpoints: ['internal: http://whisper.svc.cluster.local:8080'],
    status: 'Running',
    display_name: 'Whisper Large V3',
    model_source_type: 'namespace',
    model_type: 'transcription',
    capabilities: ['audio-transcription'],
    internalEndpoint: 'http://whisper.svc.cluster.local:8080',
    inPlayground: true,
  },
  {
    model_name: 'facebook-opt-125m',
    model_id: 'facebook-opt-125m',
    serving_runtime: 'vllm',
    api_protocol: 'openai',
    version: '1.0.0',
    usecase: 'Test case',
    description: '',
    endpoints: [],
    status: 'Pending',
    display_name: 'facebook-opt-125m',
    model_source_type: 'namespace',
    model_type: 'llm',
    capabilities: [],
    inPlayground: false,
  },
];

export const MOCK_MCP_SERVERS: MCPServer[] = [
  {
    id: 'mcp-github',
    name: 'GitHub-MCP-Server',
    url: 'http://github-mcp-server.crimson-show.svc.cluster.local:8080/sse',
    endpoint: '/sse',
    transport: 'sse',
    status: 'unknown',
    description: 'MCP server for GitHub integration',
  },
  {
    id: 'mcp-k8s',
    name: 'Kubernetes-MCP-Server',
    url: 'http://kubernetes-mcp-server.crimson-show.svc.cluster.local:8080/sse',
    endpoint: '/sse',
    transport: 'sse',
    status: 'healthy',
    description: 'MCP server for Kubernetes cluster access',
  },
  {
    id: 'mcp-slack',
    name: 'Slack-MCP-Server',
    url: 'http://slack-mcp-server.crimson-show.svc.cluster.local:8080/sse',
    endpoint: '/sse',
    transport: 'sse',
    status: 'error',
    description: 'MCP server for Slack workspace tools',
  },
];
