import type { WorkbenchRow } from './types';

/** Seeded from odh-dashboard Notebooks v2 Workspaces mock shapes (simplified). */
export const MOCK_WORKBENCHES: WorkbenchRow[] = [
  {
    id: 'wb-1',
    name: 'My Jupyter Notebook',
    image: 'JupyterLab with PyTorch',
    podConfig: 'Small GPU',
    kind: 'JupyterLab Notebook',
    state: 'Running',
    lastActivityMs: Date.now() - 1000 * 60 * 12,
    connectEndpoints: [
      { displayName: 'JupyterLab', httpPath: 'https://jupyterlab.example.com' },
      { displayName: 'Spark Master', httpPath: 'https://spark-master.example.com' },
    ],
    homeVolume: 'Volume-Home',
    dataVolumes: ['training-data'],
    packages: ['python v3.11', 'cuda v12'],
    cpu: '8',
    memory: '32Gi',
  },
  {
    id: 'wb-2',
    name: 'Fine-tune sandbox',
    image: 'JupyterLab with TensorFlow',
    podConfig: 'Medium GPU',
    kind: 'JupyterLab Notebook',
    state: 'Paused',
    lastActivityMs: new Date(2024, 11, 31).getTime(),
    connectEndpoints: [{ displayName: 'JupyterLab', httpPath: 'https://jupyterlab-2.example.com' }],
    homeVolume: 'Volume-Home',
    dataVolumes: [],
    packages: ['python v3.11', 'tensorflow v2.15'],
    cpu: '16',
    memory: '64Gi',
  },
  {
    id: 'wb-3',
    name: 'Code server workspace',
    image: 'Code Server CPU',
    podConfig: 'Large CPU',
    kind: 'Code Server',
    state: 'Pending',
    lastActivityMs: Date.now() - 1000 * 60 * 60 * 5,
    connectEndpoints: [{ displayName: 'Code Server', httpPath: 'https://code-server.example.com' }],
    homeVolume: 'Volume-Home',
    dataVolumes: ['shared-libs'],
    packages: ['node v20', 'python v3.11'],
    cpu: '8',
    memory: '16Gi',
  },
  {
    id: 'wb-4',
    name: 'Failed start example',
    image: 'JupyterLab Minimal',
    podConfig: 'Small CPU',
    kind: 'JupyterLab Notebook',
    state: 'Error',
    lastActivityMs: Date.now() - 1000 * 60 * 60 * 24,
    connectEndpoints: [],
    homeVolume: 'Volume-Home',
    dataVolumes: [],
    packages: ['python v3.11'],
    cpu: '2',
    memory: '4Gi',
  },
];
