import { ApiKeyStatusV34, ApiKeyV34 } from './typesV34';

export const mockApiKeysEngineerV34: ApiKeyV34[] = [
  {
    id: 'key-0',
    name: 'Personal Key',
    description: 'Personal development and testing key for local experiments',
    username: 'celtan',
    keyPrefix: 'sk-oai-per',
    creationDate: new Date('2025-10-01T08:00:00Z'),
    expirationDate: new Date('2026-04-01T08:00:00Z'),
    status: 'active',
    lastUsedAt: new Date('2026-01-25T09:15:00Z'),
    subscriptionId: 'standard-tier',
    subscriptionName: 'Standard Subscription',
  },
  {
    id: 'key-2',
    name: 'Dark Net Key',
    description: "Shared this key publicly — revoked by admin.",
    username: 'celtan',
    keyPrefix: 'sk-oai-drk',
    creationDate: new Date('2025-10-12T10:30:00Z'),
    expirationDate: new Date('2026-10-12T10:30:00Z'),
    status: 'revoked',
    lastUsedAt: new Date('2026-01-25T10:30:00Z'),
    subscriptionId: 'enterprise-tier',
    subscriptionName: 'Enterprise Subscription',
  },
  {
    id: 'key-5',
    name: 'Playground',
    description: 'Key for interactive playground testing and demos',
    username: 'celtan',
    keyPrefix: 'sk-oai-ply',
    creationDate: new Date('2025-10-10T14:00:00Z'),
    status: 'active',
    lastUsedAt: new Date('2026-01-25T14:00:00Z'),
    subscriptionId: 'standard-tier',
    subscriptionName: 'Standard Subscription',
  },
  {
    id: 'key-13',
    name: 'Ye Olden Key',
    description: 'Keeping this key around for good luck',
    username: 'celtan',
    keyPrefix: 'sk-oai-old',
    creationDate: new Date('2021-06-15T11:00:00Z'),
    expirationDate: new Date('2021-12-20T11:00:00Z'),
    status: 'expired',
    lastUsedAt: new Date('2021-12-20T11:00:00Z'),
  },
  {
    id: 'key-14',
    name: 'Experimental Features',
    description: 'Testing new model capabilities',
    username: 'celtan',
    keyPrefix: 'sk-oai-exp',
    creationDate: new Date('2026-01-20T09:00:00Z'),
    expirationDate: new Date('2026-02-20T09:00:00Z'),
    status: 'expired',
    lastUsedAt: new Date('2026-01-25T14:30:00Z'),
    subscriptionId: 'research-unlimited',
    subscriptionName: 'Research Unlimited',
  },
  {
    id: 'key-15',
    name: 'Legacy Batch Processing',
    description: 'Old batch job key — no longer in active use',
    username: 'celtan',
    keyPrefix: 'sk-oai-bat',
    creationDate: new Date('2025-05-10T10:00:00Z'),
    expirationDate: new Date('2026-05-10T10:00:00Z'),
    status: 'revoked',
    lastUsedAt: new Date('2025-09-15T16:45:00Z'),
    subscriptionId: 'enterprise-tier',
    subscriptionName: 'Enterprise Subscription',
  },
  {
    id: 'key-16',
    name: 'Model Serving Automation',
    description: 'Automated model deployment and serving tasks',
    username: 'celtan',
    keyPrefix: 'sk-oai-srv',
    creationDate: new Date('2025-12-01T10:00:00Z'),
    expirationDate: new Date('2026-12-01T10:00:00Z'),
    status: 'active',
    lastUsedAt: new Date('2026-01-28T15:30:00Z'),
    subscriptionId: 'enterprise-tier',
    subscriptionName: 'Enterprise Subscription',
  },
];

export const mockApiKeysAdminV34: ApiKeyV34[] = [
  {
    id: 'key-0',
    name: 'Personal Key',
    description: 'Personal development and testing key for local experiments',
    username: 'abraren',
    keyPrefix: 'sk-oai-per',
    creationDate: new Date('2025-10-01T08:00:00Z'),
    expirationDate: new Date('2026-04-01T08:00:00Z'),
    status: 'active',
    lastUsedAt: new Date('2026-01-25T09:15:00Z'),
    subscriptionId: 'standard-tier',
    subscriptionName: 'Standard Subscription',
  },
  {
    id: 'key-2',
    name: 'Production Workloads',
    description: 'High-throughput key for production customer-facing applications',
    username: 'ngrambich',
    keyPrefix: 'sk-oai-prd',
    creationDate: new Date('2025-10-12T10:30:00Z'),
    expirationDate: new Date('2026-10-12T10:30:00Z'),
    status: 'active',
    lastUsedAt: new Date('2026-01-25T10:30:00Z'),
    subscriptionId: 'enterprise-tier',
    subscriptionName: 'Enterprise Subscription',
  },
  {
    id: 'key-3',
    name: 'Research Project',
    description: 'Key for ML research team experiments with code generation models',
    username: 'cschumer',
    keyPrefix: 'sk-oai-res',
    creationDate: new Date('2025-10-12T10:30:00Z'),
    expirationDate: new Date('2026-01-18T14:20:00Z'),
    status: 'expired',
    lastUsedAt: new Date('2026-01-25T10:30:00Z'),
    subscriptionId: 'research-unlimited',
    subscriptionName: 'Research Unlimited',
  },
  {
    id: 'key-4',
    name: 'Legacy Integration',
    description: 'Deprecated key from old integration — pending removal',
    username: 'jsmith',
    keyPrefix: 'sk-oai-leg',
    creationDate: new Date('2024-08-10T10:00:00Z'),
    expirationDate: new Date('2024-09-10T10:00:00Z'),
    status: 'expired',
    lastUsedAt: new Date('2024-09-08T08:45:00Z'),
  },
  {
    id: 'key-5',
    name: 'Playground',
    description: 'Key for interactive playground testing and demos',
    username: 'abraren',
    keyPrefix: 'sk-oai-ply',
    creationDate: new Date('2025-10-10T14:00:00Z'),
    status: 'active',
    lastUsedAt: new Date('2026-01-25T14:00:00Z'),
    subscriptionId: 'standard-tier',
    subscriptionName: 'Standard Subscription',
  },
  {
    id: 'key-6',
    name: 'Customer Support Bot',
    description: 'Customer-facing chatbot key',
    username: 'mwilliams',
    keyPrefix: 'sk-oai-csb',
    creationDate: new Date('2021-07-07T10:00:00Z'),
    expirationDate: new Date('2026-03-15T10:00:00Z'),
    status: 'active',
    lastUsedAt: new Date('2022-07-07T14:30:00Z'),
    subscriptionId: 'enterprise-tier',
    subscriptionName: 'Enterprise Subscription',
  },
  {
    id: 'key-7',
    name: 'CI/CD Pipeline',
    description: 'Service account key for automated testing and deployments',
    username: 'ci-pipeline-bot',
    keyPrefix: 'sk-oai-cic',
    creationDate: new Date('2025-08-20T10:00:00Z'),
    expirationDate: new Date('2026-08-20T10:00:00Z'),
    status: 'revoked',
    lastUsedAt: new Date('2026-01-25T14:30:00Z'),
    subscriptionId: 'standard-tier',
    subscriptionName: 'Standard Subscription',
  },
  {
    id: 'key-8',
    name: 'Data Pipeline Key',
    description: 'ETL and data processing workflows',
    username: 'data-pipeline-worker',
    keyPrefix: 'sk-oai-dpl',
    creationDate: new Date('2025-09-15T09:00:00Z'),
    expirationDate: new Date('2026-09-15T09:00:00Z'),
    status: 'active',
    lastUsedAt: new Date('2026-01-28T11:30:00Z'),
    subscriptionId: 'enterprise-tier',
    subscriptionName: 'Enterprise Subscription',
  },
  {
    id: 'key-9',
    name: 'ML Training Runner',
    description: 'Automated model training and fine-tuning jobs',
    username: 'ml-training-runner',
    keyPrefix: 'sk-oai-mlt',
    creationDate: new Date('2025-11-01T14:00:00Z'),
    status: 'active',
    lastUsedAt: new Date('2026-01-27T16:45:00Z'),
    subscriptionId: 'research-unlimited',
    subscriptionName: 'Research Unlimited',
  },
  {
    id: 'key-10',
    name: 'Analytics Dashboard',
    description: 'Key for internal analytics and reporting dashboard',
    username: 'klee',
    keyPrefix: 'sk-oai-ana',
    creationDate: new Date('2025-12-05T10:00:00Z'),
    expirationDate: new Date('2026-06-05T10:00:00Z'),
    status: 'active',
    lastUsedAt: new Date('2026-01-28T09:00:00Z'),
    subscriptionId: 'standard-tier',
    subscriptionName: 'Standard Subscription',
  },
  {
    id: 'key-11',
    name: 'Chatbot Integration',
    description: 'Customer-facing chatbot powered by LLM',
    username: 'ngrambich',
    keyPrefix: 'sk-oai-cht',
    creationDate: new Date('2025-11-20T08:30:00Z'),
    expirationDate: new Date('2026-05-20T08:30:00Z'),
    status: 'active',
    lastUsedAt: new Date('2026-01-28T14:20:00Z'),
    subscriptionId: 'enterprise-tier',
    subscriptionName: 'Enterprise Subscription',
  },
  {
    id: 'key-12',
    name: 'Code Review Assistant',
    description: 'Automated code review and suggestion tool',
    username: 'cschumer',
    keyPrefix: 'sk-oai-crv',
    creationDate: new Date('2025-06-15T11:00:00Z'),
    expirationDate: new Date('2026-06-15T11:00:00Z'),
    status: 'revoked',
    lastUsedAt: new Date('2025-10-01T09:30:00Z'),
    subscriptionId: 'research-unlimited',
    subscriptionName: 'Research Unlimited',
  },
];

const heavyUserKeyNames = [
  'Inference Gateway', 'Batch Scoring', 'Model Registry Sync', 'Feature Store Access',
  'A/B Testing Controller', 'Canary Deployment', 'Shadow Traffic', 'Load Testing',
  'Staging Environment', 'Dev Sandbox', 'QA Automation', 'Integration Tests',
  'Performance Benchmarks', 'Data Labeling Pipeline', 'Annotation Service',
  'Embedding Generator', 'Vector Search', 'RAG Pipeline', 'Fine-tuning Jobs',
  'Model Export', 'ONNX Converter', 'TensorRT Optimizer', 'Monitoring Webhook',
  'Alerting Service', 'Cost Tracker', 'Prompt Caching', 'Token Counter',
  'Rate Limiter', 'Content Filter', 'Guardrails Service', 'Safety Checker',
  'Image Generation', 'Speech-to-Text', 'Text-to-Speech', 'Translation API',
  'Summarization Engine', 'Classification Service', 'Sentiment Analyzer',
  'Entity Extractor', 'Document Parser', 'PDF Processor', 'OCR Pipeline',
  'Knowledge Graph', 'Recommendation Engine', 'Personalization API',
  'Search Ranking', 'Autocomplete Service', 'Spell Checker', 'Grammar API',
  'Code Completion', 'Code Review Bot', 'Test Generator', 'Doc Generator',
  'API Gateway Prod', 'API Gateway Staging', 'API Gateway Dev',
  'Webhook Relay', 'Event Processor', 'Stream Processor', 'Queue Worker',
  'Backup Service', 'Migration Tool', 'Health Monitor', 'Log Aggregator',
  'Metrics Collector', 'Dashboard Backend', 'Admin Console', 'User Portal',
  'Mobile Backend', 'Desktop Client', 'CLI Tool', 'SDK Integration',
  'Partner API', 'Vendor Integration', 'SSO Bridge', 'Auth Proxy',
  'Data Export', 'Compliance Audit', 'Usage Reporter', 'Billing Sync',
  'Sandbox Alpha', 'Sandbox Beta', 'Sandbox Gamma', 'Canary Prod',
  'Blue-Green Deploy', 'Feature Flag Service', 'Experiment Tracker',
  'Model Versioning', 'Artifact Store', 'Pipeline Orchestrator',
  'GPU Scheduler', 'Resource Manager', 'Quota Enforcer', 'Cluster Monitor',
];

const heavyUserSubscriptions = [
  { id: 'enterprise-tier', name: 'Enterprise Subscription' },
  { id: 'standard-tier', name: 'Standard Subscription' },
  { id: 'research-unlimited', name: 'Research Unlimited' },
];

export const mockHeavyUserKeysV34: ApiKeyV34[] = heavyUserKeyNames.map((name, i) => {
  const statuses: ApiKeyStatusV34[] = ['active', 'active', 'active', 'revoked', 'expired'];
  const created = new Date(2025, 0 + Math.floor(i / 3), 5 + i, 9, 0);
  const expiration = new Date(created);
  expiration.setMonth(expiration.getMonth() + 6);
  const lastUsed = new Date(2026, 1, 28 - i, 10 + (i % 12), i * 2);
  const sub = heavyUserSubscriptions[i % heavyUserSubscriptions.length];
  return {
    id: `key-heavy-${i}`,
    name,
    description: `Key for ${name.toLowerCase()} workload`,
    username: 'celtan',
    keyPrefix: `sk-oai-h${String(i).padStart(2, '0')}`,
    creationDate: created,
    expirationDate: i % 5 === 0 ? undefined : expiration,
    status: statuses[i % statuses.length],
    lastUsedAt: lastUsed,
    subscriptionId: sub.id,
    subscriptionName: sub.name,
  };
});

export const getApiKeyByIdV34 = (id: string, isAdmin: boolean): ApiKeyV34 | undefined => {
  const keys = isAdmin ? mockApiKeysAdminV34 : mockApiKeysEngineerV34;
  return keys.find((k) => k.id === id);
};
